package syscallsenter

var sysCallsEnter = map[string]string{
	"setresgid":               "rgid egid sgid",
	"setsid":                  "",
	"reboot":                  "magic1 magic2 cmd arg",
	"copy_file_range":         "fd_in off_in fd_out off_out len flags",
	"open":                    "filename flags mode",
	"newfstatat":              "dfd filename statbuf flag",
	"chmod":                   "filename mode",
	"remap_file_pages":        "start size prot pgoff flags",
	"clock_settime":           "which_clock tp",
	"sched_getparam":          "pid param",
	"timer_delete":            "timer_id",
	"eventfd":                 "count",
	"sendfile64":              "out_fd in_fd offset count",
	"futex_waitv":             "waiters nr_futexes flags timeout clockid",
	"bind":                    "fd umyaddr addrlen",
	"chown":                   "filename user group",
	"renameat":                "olddfd oldname newdfd newname",
	"epoll_wait":              "epfd events maxevents timeout",
	"setregid":                "rgid egid",
	"epoll_create1":           "flags",
	"timerfd_gettime":         "ufd otmr",
	"setsockopt":              "fd level optname optval optlen",
	"dup3":                    "oldfd newfd flags",
	"keyctl":                  "option arg2 arg3 arg4 arg5",
	"newuname":                "name",
	"pidfd_getfd":             "pidfd fd flags",
	"sethostname":             "name len",
	"process_vm_writev":       "pid lvec liovcnt rvec riovcnt flags",
	"recvmsg":                 "fd msg flags",
	"clock_adjtime":           "which_clock utx",
	"mount_setattr":           "dfd path flags uattr usize",
	"dup":                     "fildes",
	"syslog":                  "type buf len",
	"tkill":                   "pid sig",
	"io_uring_enter":          "fd to_submit min_complete flags argp argsz",
	"fchmodat":                "dfd filename mode",
	"getxattr":                "pathname name value size",
	"sched_setscheduler":      "pid policy param",
	"fdatasync":               "fd",
	"faccessat":               "dfd filename mode",
	"brk":                     "brk",
	"rename":                  "oldname newname",
	"rt_sigprocmask":          "how nset oset sigsetsize",
	"rt_sigsuspend":           "unewset sigsetsize",
	"ioprio_get":              "which who",
	"msgget":                  "key msgflg",
	"timerfd_create":          "clockid flags",
	"kill":                    "pid sig",
	"lremovexattr":            "pathname name",
	"acct":                    "name",
	"memfd_secret":            "flags",
	"clock_nanosleep":         "which_clock flags rqtp rmtp",
	"close":                   "fd",
	"flock":                   "fd cmd",
	"fremovexattr":            "fd name",
	"lseek":                   "fd offset whence",
	"getdents":                "fd dirent count",
	"migrate_pages":           "pid maxnode old_nodes new_nodes",
	"getrusage":               "who ru",
	"setitimer":               "which value ovalue",
	"getcwd":                  "buf size",
	"readlink":                "path buf bufsiz",
	"getpgrp":                 "",
	"statx":                   "dfd filename flags mask buffer",
	"utimes":                  "filename utimes",
	"rseq":                    "rseq rseq_len flags sig",
	"init_module":             "umod len uargs",
	"sched_get_priority_min":  "policy",
	"semop":                   "semid tsops nsops",
	"perf_event_open":         "attr_uptr pid cpu group_fd flags",
	"fchmod":                  "fd mode",
	"pivot_root":              "new_root put_old",
	"fstatfs":                 "fd buf",
	"fsync":                   "fd",
	"io_cancel":               "ctx_id iocb result",
	"time":                    "tloc",
	"timer_settime":           "timer_id flags new_setting old_setting",
	"newfstat":                "fd statbuf",
	"io_uring_setup":          "entries params",
	"pidfd_open":              "pid flags",
	"listen":                  "fd backlog",
	"set_mempolicy":           "mode nmask maxnode",
	"msgctl":                  "msqid cmd buf",
	"sysinfo":                 "info",
	"sched_getattr":           "pid uattr usize flags",
	"pipe":                    "fildes",
	"clock_gettime":           "which_clock tp",
	"lsetxattr":               "pathname name value size flags",
	"getitimer":               "which value",
	"signalfd4":               "ufd user_mask sizemask flags",
	"epoll_create":            "size",
	"fanotify_init":           "flags event_f_flags",
	"prctl":                   "option arg2 arg3 arg4 arg5",
	"set_tid_address":         "tidptr",
	"readlinkat":              "dfd pathname buf bufsiz",
	"swapon":                  "specialfile swap_flags",
	"ioctl":                   "fd cmd arg",
	"openat2":                 "dfd filename how usize",
	"landlock_add_rule":       "ruleset_fd rule_type rule_attr flags",
	"futimesat":               "dfd filename utimes",
	"clock_getres":            "which_clock tp",
	"rt_sigqueueinfo":         "pid sig uinfo",
	"rt_sigtimedwait":         "uthese uinfo uts sigsetsize",
	"open_tree":               "dfd filename flags",
	"preadv":                  "fd vec vlen pos_l pos_h",
	"setns":                   "fd flags",
	"mbind":                   "start len mode nmask maxnode flags",
	"getsockname":             "fd usockaddr usockaddr_len",
	"select":                  "n inp outp exp tvp",
	"waitid":                  "which upid infop options ru",
	"pidfd_send_signal":       "pidfd sig info flags",
	"link":                    "oldname newname",
	"setpgid":                 "pid pgid",
	"socket":                  "family type protocol",
	"rmdir":                   "pathname",
	"close_range":             "fd max_fd flags",
	"umask":                   "mask",
	"fadvise64":               "fd offset len advice",
	"fsconfig":                "fd cmd _key _value aux",
	"process_vm_readv":        "pid lvec liovcnt rvec riovcnt flags",
	"getgroups":               "gidsetsize grouplist",
	"mknodat":                 "dfd filename mode dev",
	"delete_module":           "name_user flags",
	"tee":                     "fdin fdout len flags",
	"finit_module":            "fd uargs flags",
	"prlimit64":               "pid resource new_rlim old_rlim",
	"get_mempolicy":           "policy nmask maxnode addr flags",
	"recvfrom":                "fd ubuf size flags addr addr_len",
	"rt_tgsigqueueinfo":       "tgid pid sig uinfo",
	"kexec_file_load":         "kernel_fd initrd_fd cmdline_len cmdline_ptr flags",
	"statfs":                  "pathname buf",
	"symlinkat":               "oldname newdfd newname",
	"epoll_ctl":               "epfd op fd event",
	"io_getevents":            "ctx_id min_nr nr events timeout",
	"truncate":                "path length",
	"exit":                    "error_code",
	"setfsgid":                "gid",
	"settimeofday":            "tv tz",
	"chroot":                  "filename",
	"swapoff":                 "specialfile",
	"epoll_pwait2":            "epfd events maxevents timeout sigmask sigsetsize",
	"munmap":                  "addr len",
	"writev":                  "fd vec vlen",
	"creat":                   "pathname mode",
	"seccomp":                 "op flags uargs",
	"fcntl":                   "fd cmd arg",
	"vmsplice":                "fd uiov nr_segs flags",
	"write":                   "fd buf count",
	"open_by_handle_at":       "mountdirfd handle flags",
	"utimensat":               "dfd filename utimes flags",
	"setreuid":                "ruid euid",
	"readahead":               "fd offset count",
	"sysfs":                   "option arg1 arg2",
	"eventfd2":                "count flags",
	"faccessat2":              "dfd filename mode flags",
	"inotify_rm_watch":        "fd wd",
	"userfaultfd":             "flags",
	"membarrier":              "cmd flags cpu_id",
	"quotactl":                "cmd special id addr",
	"readv":                   "fd vec vlen",
	"getppid":                 "",
	"epoll_pwait":             "epfd events maxevents timeout sigmask sigsetsize",
	"execveat":                "fd filename argv envp flags",
	"fsmount":                 "fs_fd flags attr_flags",
	"set_mempolicy_home_node": "start len home_node flags",
	"mknod":                   "filename mode dev",
	"shmget":                  "key size shmflg",
	"request_key":             "_type _description _callout_info destringid",
	"io_destroy":              "ctx",
	"sendmmsg":                "fd mmsg vlen flags",
	"shmdt":                   "shmaddr",
	"modify_ldt":              "func ptr bytecount",
	"mq_notify":               "mqdes u_notification",
	"rt_sigaction":            "sig act oact sigsetsize",
	"gettid":                  "",
	"llistxattr":              "pathname list size",
	"accept":                  "fd upeer_sockaddr upeer_addrlen",
	"quotactl_fd":             "fd cmd id addr",
	"getpgid":                 "pid",
	"semget":                  "key nsems semflg",
	"clone":                   "clone_flags newsp parent_tidptr child_tidptr tls",
	"getuid":                  "",
	"msync":                   "start len flags",
	"ioprio_set":              "which who ioprio",
	"io_submit":               "ctx_id nr iocbpp",
	"fallocate":               "fd mode offset len",
	"fsopen":                  "_fs_name flags",
	"ftruncate":               "fd length",
	"geteuid":                 "",
	"socketpair":              "family type protocol usockvec",
	"munlock":                 "start len",
	"timer_create":            "which_clock timer_event_spec created_timer_id",
	"accept4":                 "fd upeer_sockaddr upeer_addrlen flags",
	"mlockall":                "flags",
	"nanosleep":               "rqtp rmtp",
	"sched_getscheduler":      "pid",
	"semtimedop":              "semid tsops nsops timeout",
	"kexec_load":              "entry nr_segments segments flags",
	"poll":                    "ufds nfds timeout_msecs",
	"getcpu":                  "cpup nodep unused",
	"adjtimex":                "txc_p",
	"read":                    "fd buf count",
	"execve":                  "filename argv envp",
	"timer_getoverrun":        "timer_id",
	"connect":                 "fd uservaddr addrlen",
	"name_to_handle_at":       "dfd name handle mnt_id flag",
	"timer_gettime":           "timer_id setting",
	"access":                  "filename mode",
	"setresuid":               "ruid euid suid",
	"shmat":                   "shmid shmaddr shmflg",
	"mlock2":                  "start len flags",
	"restart_syscall":         "",
	"setfsuid":                "uid",
	"fchdir":                  "fd",
	"ustat":                   "dev ubuf",
	"fgetxattr":               "fd name value size",
	"mincore":                 "start len vec",
	"renameat2":               "olddfd oldname newdfd newname flags",
	"get_robust_list":         "pid head_ptr len_ptr",
	"syncfs":                  "fd",
	"pause":                   "",
	"vfork":                   "",
	"fsetxattr":               "fd name value size flags",
	"tgkill":                  "tgid pid sig",
	"umount":                  "name flags",
	"pread64":                 "fd buf count pos",
	"recvmmsg":                "fd mmsg vlen flags timeout",
	"splice":                  "fd_in off_in fd_out off_out len flags",
	"io_pgetevents":           "ctx_id min_nr nr events timeout usig",
	"setgid":                  "gid",
	"pkey_mprotect":           "start len prot pkey",
	"alarm":                   "seconds",
	"msgsnd":                  "msqid msgp msgsz msgflg",
	"newlstat":                "filename statbuf",
	"newstat":                 "filename statbuf",
	"iopl":                    "level",
	"pkey_free":               "pkey",
	"bpf":                     "cmd uattr size",
	"capget":                  "header dataptr",
	"personality":             "personality",
	"fchownat":                "dfd filename user group flag",
	"flistxattr":              "fd list size",
	"process_madvise":         "pidfd vec vlen behavior flags",
	"sched_setparam":          "pid param",
	"unshare":                 "unshare_flags",
	"landlock_restrict_self":  "ruleset_fd flags",
	"vhangup":                 "",
	"ppoll":                   "ufds nfds tsp sigmask sigsetsize",
	"getresgid":               "rgidp egidp sgidp",
	"clone3":                  "uargs size",
	"mq_timedreceive":         "mqdes u_msg_ptr msg_len u_msg_prio u_abs_timeout",
	"pipe2":                   "fildes flags",
	"landlock_create_ruleset": "attr size flags",
	"removexattr":             "pathname name",
	"mq_unlink":               "u_name",
	"io_setup":                "nr_events ctxp",
	"setgroups":               "gidsetsize grouplist",
	"preadv2":                 "fd vec vlen pos_l pos_h flags",
	"semctl":                  "semid semnum cmd arg",
	"memfd_create":            "uname flags",
	"capset":                  "header data",
	"move_pages":              "pid nr_pages pages nodes status flags",
	"rt_sigpending":           "uset sigsetsize",
	"rt_sigreturn":            "",
	"process_mrelease":        "pidfd flags",
	"pselect6":                "n inp outp exp tsp sig",
	"getsockopt":              "fd level optname optval optlen",
	"sched_getaffinity":       "pid len user_mask_ptr",
	"lchown":                  "filename user group",
	"getrandom":               "ubuf len flags",
	"getsid":                  "pid",
	"inotify_init":            "",
	"add_key":                 "_type _description _payload plen ringid",
	"getdents64":              "fd dirent count",
	"setuid":                  "uid",
	"chdir":                   "filename",
	"getpriority":             "which who",
	"munlockall":              "",
	"openat":                  "dfd filename flags mode",
	"futex":                   "uaddr op val utime uaddr2 val3",
	"getpeername":             "fd usockaddr usockaddr_len",
	"shutdown":                "fd how",
	"sigaltstack":             "uss uoss",
	"mq_open":                 "u_name oflag mode u_attr",
	"timerfd_settime":         "ufd flags utmr otmr",
	"arch_prctl":              "option arg2",
	"getegid":                 "",
	"signalfd":                "ufd user_mask sizemask",
	"sync_file_range":         "fd offset nbytes flags",
	"ioperm":                  "from num turn_on",
	"move_mount":              "from_dfd from_pathname to_dfd to_pathname flags",
	"sync":                    "",
	"dup2":                    "oldfd newfd",
	"fork":                    "",
	"madvise":                 "start len_in behavior",
	"getresuid":               "ruidp euidp suidp",
	"gettimeofday":            "tv tz",
	"setrlimit":               "resource rlim",
	"getrlimit":               "resource rlim",
	"sched_rr_get_interval":   "pid interval",
	"kcmp":                    "pid1 pid2 type idx1 idx2",
	"mkdir":                   "pathname mode",
	"mkdirat":                 "dfd pathname mode",
	"mmap":                    "addr len prot flags fd off",
	"mount":                   "dev_name dir_name type flags data",
	"pwritev":                 "fd vec vlen pos_l pos_h",
	"unlink":                  "pathname",
	"mq_timedsend":            "mqdes u_msg_ptr msg_len msg_prio u_abs_timeout",
	"symlink":                 "oldname newname",
	"inotify_init1":           "flags",
	"ptrace":                  "request pid addr data",
	"pwrite64":                "fd buf count pos",
	"pwritev2":                "fd vec vlen pos_l pos_h flags",
	"setxattr":                "pathname name value size flags",
	"mq_getsetattr":           "mqdes u_mqstat u_omqstat",
	"sched_setattr":           "pid uattr flags",
	"wait4":                   "upid stat_addr options ru",
	"sched_get_priority_max":  "policy",
	"unlinkat":                "dfd pathname flag",
	"utime":                   "filename times",
	"pkey_alloc":              "flags init_val",
	"lgetxattr":               "pathname name value size",
	"io_uring_register":       "fd opcode arg nr_args",
	"fchown":                  "fd user group",
	"linkat":                  "olddfd oldname newdfd newname flags",
	"listxattr":               "pathname list size",
	"set_robust_list":         "head len",
	"mremap":                  "addr old_len new_len flags new_addr",
	"inotify_add_watch":       "fd pathname mask",
	"sched_yield":             "",
	"fspick":                  "dfd path flags",
	"getgid":                  "",
	"times":                   "tbuf",
	"sendto":                  "fd buff len flags addr addr_len",
	"setpriority":             "which who niceval",
	"shmctl":                  "shmid cmd buf",
	"sendmsg":                 "fd msg flags",
	"setdomainname":           "name len",
	"mlock":                   "start len",
	"mprotect":                "start len prot",
	"sched_setaffinity":       "pid len user_mask_ptr",
	"exit_group":              "error_code",
	"getpid":                  "",
	"msgrcv":                  "msqid msgp msgsz msgtyp msgflg",
	"fanotify_mark":           "fanotify_fd flags mask dfd pathname",
}

func Exists(syscall string) bool {
	_, ok := sysCallsEnter[syscall]
	return ok
}

func GetArgs(syscall string) {

}

func SetSyscalls(syscalls map[string]string) {
	sysCallsEnter = syscalls
}
